#!/usr/bin/env bash
#
# Downloads the emulator APKs pinned in emulators/apks.lock from F-Droid,
# verifies them and regenerates the files the build needs:
#
#   emulators/preinstall/<name>.apk        untouched F-Droid APK (git LFS)
#   emulators/preinstall/NOTICE-<name>.txt license + where to get the source
#   emulators/preinstall/preinstall.list   what the first-boot service installs
#
# usage: fetch-apks.sh [--sources DIR]
#
#   --sources  also download F-Droid's source tarball for every APK into DIR
#              (not needed for releases, the NOTICE points at the upstream source)

set -euo pipefail

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
LOCK=$HERE/apks.lock
OUT=$HERE/preinstall
MIRRORS="https://f-droid.org/repo https://f-droid.org/archive"
SOURCES=

while [ $# -gt 0 ]; do
	case $1 in
		--sources) SOURCES=$2; shift 2 ;;
		-h|--help) sed -n '2,14p' "$0"; exit 0 ;;
		*) echo "unknown option: $1" >&2; exit 1 ;;
	esac
done

die() { echo "error: $*" >&2; exit 1; }

# fetch <file> <dest> ; tries the live repo first, then the archive
fetch() {
	local m
	for m in $MIRRORS; do
		curl -fsSL -o "$2.part" "$m/$1" && { mv "$2.part" "$2"; return 0; }
	done
	rm -f "$2.part"
	return 1
}

mkdir -p "$OUT"
[ -n "$SOURCES" ] && mkdir -p "$SOURCES"
list=$OUT/preinstall.list.new
echo "# package versionCode apk  (generated by scripts/fetch-apks.sh)" >"$list"

while read -r name pkg vc vname spdx sha license_url; do
	case $name in ''|\#*) continue ;; esac
	apk=$OUT/$name.apk

	if [ -f "$apk" ] && echo "$sha  $apk" | sha256sum -c - >/dev/null 2>&1; then
		echo ">> $name $vname already up to date"
	else
		echo ">> $name $vname"
		fetch "${pkg}_${vc}.apk" "$apk" || die "$name: download failed"
		echo "$sha  $apk" | sha256sum -c - >/dev/null || { rm -f "$apk"; die "$name: checksum mismatch"; }
	fi

	{
		echo "$name $vname ($pkg, versionCode $vc) - $spdx"
		echo
		echo "Shipped unmodified as published by F-Droid (sha256 $sha)."
		# The license URL points into the upstream repository at the release tag
		ref=${license_url#https://raw.githubusercontent.com/}
		echo "Source: https://github.com/$(echo "$ref" | cut -d/ -f1-2)/tree/$(echo "$ref" | cut -d/ -f3)"
		echo
		echo "================================================================================"
		curl -fsSL "$license_url" || die "$name: could not fetch license text"
	} >"$OUT/NOTICE-$name.txt"

	echo "$pkg $vc $name.apk" >>"$list"

	if [ -n "$SOURCES" ]; then
		src=$SOURCES/${pkg}_${vc}_src.tar.gz
		[ -f "$src" ] || fetch "${pkg}_${vc}_src.tar.gz" "$src" || die "$name: source download failed"
	fi
done <"$LOCK"

mv "$list" "$OUT/preinstall.list"
